language: python

python:
  - "2.7"

# Twisted is required for trial.
install:
  - pip install --upgrade twisted==13.2.0 pyflakes==0.8.1 .

script:
  - trial twistedchecker
  - python ./check_pyflakes.py ./twistedchecker setup.py

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: twistedchecker-robot
  password:
    secure: ENCRYPTED-VALUE HERE
  on:
    tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
