language: python

python:
  - "2.7"

# command to install dependencies
install: "pip install twisted==13.2.0 ."

script: trial twistechecker

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"
