language: python

python:
  - "2.7"

install:
  - pip install --upgrade -e '.[dev]'

script:
  - trial twistedchecker
  - python ./check_pyflakes.py ./twistedchecker setup.py

  # Ensure the script was installed on $PATH
  - python setup.py install
  - cd /
  - twistedchecker -h

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"

# Travis is a bit "simple" and will not automatically switch to the
# deployment directory before running its own deploy code.
before_deploy:
    - cd $TRAVIS_BUILD_DIR

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  # twistedchecker-robot is associated with adi.roiban email address from
  # Gmail. It uses a random password which was not recorded in plain text.
  user: twistedchecker-robot
  password:
    secure: VS3uq3pdprwQUQmMFlS0ieXTX7UKvNjAQi/6CXfxqcJVlExVojsiSwOIgE76r74TuLRKDzlYD+G6dGkvaRmlfV2GVMhChUCN71Y0QtFPB68M9MuFyf/ICHb0zhs2f53/86m+ThphCOQwnOYxDeramR4TAsQR95buDO2Ko590vnQ=
  on:
    # tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
