language: python

python:
  - "2.7"

install:
  - pip install --upgrade -e '.[dev]'

script:
  - trial twistedchecker
  - python ./check_pyflakes.py ./twistedchecker setup.py

  # Ensure the script was installed on $PATH
  - python setup.py install
  - cd /
  - twistedchecker -h

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: twistedchecker-robot
  password:
    secure: ENCRYPTED-VALUE HERE
  on:
    tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
