language: python

python:
  - "2.7"

install:
  - pip install --upgrade -e '.[dev]'

script:
  - trial twistedchecker
  - python ./check_pyflakes.py ./twistedchecker setup.py

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"
