language: python

python:
  - "2.7"

install:
  - pip install --upgrade -e '.[dev]'

script:
  - trial twistedchecker
  - python ./check_pyflakes.py ./twistedchecker setup.py

  # Ensure the script was installed on $PATH
  - python setup.py install
  - cd /
  - twistedchecker -h

# Dump trial log on failure.
after_failure: "cat _trial_temp/test.log"
